spring.application.name=Job_Application_Tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/job_application_tracker
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.jpa.hibernate.ddl-auto=update
